server:
  port: 8080

spring:
    datasource:
        name:
        url:
        username:
        password:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  type-aliases-package: com.jingji.*.model

email:
  encode: UTF8
  host:
  account:
  password:
  port:
  auth: true
  sendTo: wangbaohe@shenz.picc.com.cn

sms:
  url: